Написание разметки для index страницы
htmlacademy-htmlcss/2006355-device-33 pull request #2
Opened 2022-01-24 22:56 UTC by liketurbo

2022-01-25 06:35 UTC, hen04 requested changes
Рамзан, в целом хорошая разметка. Есть несколько однотипных недочетов и неточностей, я о них написала. Поправь их, пожалуйста, и можно идти  дальше. 
Понравилось, что ты написал role и написал комментарии к коду, это хорошая практика.

2022-01-25 06:35 UTC, ndeg-web commented on index.html
> +      >
В верстке не принято переносить атрибуты на новую строчку: https://codeguide.academy/html-css.html#html-tags-formatting. Код раздувается, тяжелее читать.

2022-01-25 06:35 UTC, ndeg-web commented on index.html
> +      <img class="logo" src="" alt='Логотип "Device"' />
Кавычки в атрибутах везде двойные можно использовать. https://codeguide.academy/html-css.html#html-attr-double-quotes
<img class="logo" src="" alt="Логотип Барбершопа «Бородинский»."> В лекции был такой пример, можно кавычки сделать типа «таких»

2022-01-25 06:35 UTC, hen04 commented on index.html
> +      </nav>
Я бы здесь разделила элементы: Войти отдельно, Сравнить -- отдельно и Корзина -- отдельно. Список -- это то, что связано между собой, например, список элементов меню, список карточек товаров. А здесь нет логической составляющей списка.

2022-01-25 06:35 UTC, hen04 commented on index.html
> +        <ul class="dropdown-list">
Я думаю, здесь достаточно сделать иконку плюсика и все. Выпадающий список не нужно будет делать

2022-01-25 06:35 UTC, hen04 commented on index.html
> +      </button>
Это не кнопка, а ссылка на страницу Каталога. Иконка плюса может быть кнопкой с выпадающим списком, но Каталог я бы сделала ссылкой.

2022-01-25 06:35 UTC, hen04 commented on index.html
> +          <p class="promo-title">Порхает как бабочка, жалит как пчела!</p>
Выглядит как заголовок, я бы и сделала это заголовком

2022-01-25 06:35 UTC, hen04 commented on index.html
> +          </p>
https://codeguide.academy/html-css.html#html-tags-formatting -- Текст внутри тегов остаётся на одной строке с тегами

2022-01-25 06:35 UTC, hen04 commented on index.html
> +      </article>
сюда section подойдет лучше. article -- отделяемый от сайта смысловой раздел. А здесь даже не смысловой раздел, а секция или блок с контентом

2022-01-25 06:35 UTC, hen04 commented on index.html
> +
Здесь немножко по семантике странно выходит: ты вкладываешь секции в див, но по логике, все это большая секция -- accordion-wrapper, в которую входят дивы accordion-section, их на самом деле можно назвать accordion-item

2022-01-25 06:35 UTC, hen04 commented on index.html
> +          <input class="newsletter-input" name="email" type="email" required />
В input еще можно добавить атрибут placeholder="Ваш e-mail", это подсказка для пользователя

2022-01-25 06:35 UTC, hen04 commented on index.html
> +        <img class="logo logo-alt" src="" alt='Логотип "Device"' />
Здесь такая же коммент, как выше, к хедеру

2022-01-25 06:35 UTC, hen04 commented on index.html
> +          <img class="academy-logo" src="" alt='Логотип "HTML Academy"' />
<img class="logo" src="" alt="Логотип Барбершопа «Бородинский»."> В лекции был такой пример, можно кавычки сделать типа «таких»

2022-01-25 06:35 UTC, hen04 commented on index.html
> +    <meta charset="utf-8" />
Без слеша: https://codeguide.academy/html-css.html#html-closed-tag

2022-01-26 02:00 UTC, liketurbo commented on index.html
> +      >
Снес prettier, проблема ушла

2022-01-26 02:00 UTC, liketurbo commented on index.html
> +      </nav>
Вынес как отдельные ссылки

2022-01-26 02:01 UTC, liketurbo commented on index.html
> +      </button>
Разделил кнопку и ссылку

2022-01-26 02:02 UTC, liketurbo commented on index.html
> +
Заменил section(ы) на лист

2022-01-26 02:04 UTC, liketurbo commented on index.html
> +        <img class="logo logo-alt" src="" alt='Логотип "Device"' />
Нашел хорошую статью по кавычкам [§ 104. Кавычки - Студия Артемия Лебедева](https://www.artlebedev.ru/kovodstvo/sections/104/)

2022-01-26 02:06 UTC, liketurbo commented on index.html
> +    <meta charset="utf-8" />
Ох, уж этот prettier. Опять)

2022-01-26 06:09 UTC, hen04 requested changes
Рамзан, хорошо получилось!
Есть несколько замечаний, поправь их, пожалуйста, и можно идти дальше.

2022-01-26 06:09 UTC, ndeg-web commented on index.html
> +        <li class="accordion-select-item" aria-controls="accordion-section-2">
Тут опечатка )) `accordion-section-3`

2022-01-26 06:09 UTC, ndeg-web commented on index.html
> +          <h3 class="accordion-title">Кредит</h3>
Здесь тоже наверное нужен класс ` visually-hidden`, как в Гарантии

2022-01-26 06:09 UTC, ndeg-web commented on index.html
> +    <div class="features-accordion">
мне кажется, здесь и `section `хорошо пойдет

2022-01-26 06:09 UTC, ndeg-web commented on index.html
> +    <article class="special-delivery">
Тут лучше будет `section`

2022-01-26 06:09 UTC, hen04 commented on index.html
> +    <a class="small-link compare-link" href="#">Сравнить</a>
Не заметила в прошлый раз, тут нужна еще иконка сравнения

2022-01-26 06:09 UTC, hen04 commented on index.html
> +    <a class="small-link cart-link" href="#">Корзина</a>
А тут иконка корзины и количество товаров в корзине

2022-01-26 06:09 UTC, hen04 commented on catalog.html
> +                  Черный <input class="control-input" type="checkbox" name="black" checked>
Тут наверное надо местами поменять, в макете сначала чекбокс, а затем надпись к нему

2022-01-26 06:09 UTC, hen04 commented on catalog.html
> +        <h3 class="visually-hidden">Сами продукты</h3>
Может быть Список продуктов лучше будет?

2022-01-26 06:09 UTC, hen04 commented on catalog.html
> +      <hr class="dash dash-alt footer-address-dash">
Ой, как много классов на один hr )) Можно оставить какой-нибудь один

2022-01-31 23:27 UTC, liketurbo commented on index.html
> +        <li class="accordion-select-item" aria-controls="accordion-section-2">
Пипец, вы хорошо заметитили эту опечатку)

2022-01-31 23:28 UTC, liketurbo commented on index.html
> +          <h3 class="accordion-title">Кредит</h3>
Если родитель уже visually-hidden, то детям тоже надо ставить этот класс?

2022-01-31 23:28 UTC, liketurbo commented on index.html
> +    <div class="features-accordion">
Ахх, я переделывал как раз, чтобы сделать section и забыл изменить tag

2022-01-31 23:28 UTC, liketurbo commented on index.html
> +    <article class="special-delivery">
Тут я сомневался насчет section(а), потому что из текста тут только заголовок

2022-01-31 23:28 UTC, liketurbo commented on index.html
> +    <a class="small-link compare-link" href="#">Сравнить</a>
Добавил svg из макета

2022-01-31 23:28 UTC, liketurbo commented on index.html
> +    <a class="small-link cart-link" href="#">Корзина</a>
Добавил

2022-01-31 23:48 UTC, liketurbo commented on catalog.html
> +      <hr class="dash dash-alt footer-address-dash">
Оставил max два класса

2022-02-01 05:51 UTC, hen04 approved these changes
Рамзан, все хорошо!
Написала пару комментов, они не критичные, поправь, пожалуйста, в следующих коммитах. 
Можно двигаться дальше.

2022-02-01 05:51 UTC, hen04 commented on catalog.html
> +      </svg>
Рамзан, не спеши изображения вставлять в код, я бы отнесла это к декоративным изображениям и убрала бы в стили, так и код разметки чище, и правильно методологически.

2022-02-01 05:51 UTC, hen04 commented on catalog.html
> +      <input class="search-input" name="search" type="search" placeholder="Текст поиска" required>
Нужно `<input>` обернуть в `<label>`, см. [Критерий](https://up.htmlacademy.ru/htmlcss/33/criteries#HTML-05)

2022-02-01 05:51 UTC, hen04 commented on catalog.html
> +
Тут и ниже -- думаю, что стоит убрать это в стили (Если не слушал лекцию по Графике и базовой стилизации), то пока удали эти свг. В третьей лекции разбирают, что делать с ними.

2022-02-01 05:51 UTC, hen04 commented on catalog.html
> +    </div>
Смотри, в макете есть развернутое состояние пунктов меню Каталога 
[Ссылка](https://www.figma.com/file/f8ZtnZcdWC2pSklG1ssm9K/HTML-1-%2F-%D0%94%D0%B5%D0%B2%D0%B0%D0%B9%D1%81?node-id=11534%3A6989)

2022-02-01 05:51 UTC, hen04 commented on index.html
> +          <h3 class="accordion-title">Кредит</h3>
Нет, дети все будут скрыты, так как скрыт родитель

2022-02-01 05:51 UTC, merged

2022-02-03 03:04 UTC, liketurbo commented on catalog.html
> +      <input class="search-input" name="search" type="search" placeholder="Текст поиска" required>
Стоит ли оборачивать `<input>` в `<label>` при отсутствии подписи?