Базовая стилизация
htmlacademy-htmlcss/2006355-device-33 pull request #4
Opened 2022-02-10 09:23 UTC by liketurbo

2022-02-10 16:11 UTC, hen04 requested changes

2022-02-10 16:11 UTC, hen04 commented on catalog.html
> +  <link rel="stylesheet" href="./styles/base.css">
ой, на этом курсе мы пишем стили в одном файлике. На следующем,  где препроцессоры, там можно разбивать на логические блоки, а здесь сделай, пожалуйста, в одном ))

2022-02-10 16:11 UTC, hen04 commented on catalog.html
> +          <button class="button            " type="submit">Показать</button>
Не должно быть пробелов между `button` и кавычкой. Если посмотреть на это в браузере, то получается, что кнопка растягивается в высоту из-за этих пробелов

2022-02-10 16:11 UTC, hen04 commented on index.html
> +          <a class="header-2 content-nav-link" href="#">Гарантия</a>
Не совсем поняла, зачем здесь класс `header-2`. Стили достаточно прописать к классу `content-nav-link`.

2022-02-10 16:11 UTC, hen04 commented on index.html
> +      <u l class="social-list">
Тут лишний пробел ))

2022-02-10 16:11 UTC, hen04 commented on styles/base.css
> +  line-height: 21;
Здесь нужно обязательно указать `px`, иначе кнопка расползается

2022-02-13 10:19 UTC, merged

2022-02-27 11:48 UTC, liketurbo commented on catalog.html
> +          <button class="button            " type="submit">Показать</button>
Не знаю, откуда он там взялся 🤔

2022-02-27 11:48 UTC, liketurbo commented on catalog.html
> +  <link rel="stylesheet" href="./styles/base.css">
Done

2022-02-27 11:49 UTC, liketurbo commented on index.html
> +          <a class="header-2 content-nav-link" href="#">Гарантия</a>
Убрал `content-nav-link`

2022-02-27 11:50 UTC, liketurbo commented on index.html
> +      <u l class="social-list">
Очень странно 🤔, убрал

2022-02-27 11:51 UTC, liketurbo commented on styles/base.css
> +  line-height: 21;
Не заметил, поставил `px`